@startuml
interface com.example.parasol.network.CurrentUvApiService {
+ UvResponse getIndexes(Double,Double)
}

class com.example.parasol.utils.useCases.FetchUVDataUseCase {
+ <<Create>> FetchUVDataUseCase(CurrentUvApiService)
+ UvResponse invoke(Double,Double)
}

class com.example.parasol.data.UserPreferencesRepository$PreferencesKeys {
+  SELECTED_CITY
}

class com.example.parasol.data.UserPreferencesRepository {
+ Flow<String?> selectedCityFlow
+ <<Create>> UserPreferencesRepository(Context)
+ void saveSelectedCity(String)
}


interface com.example.parasol.data.CityDao {
+ void insert(CityEntity)
+ void update(CityEntity)
+ void delete(CityEntity)
+ Flow<CityEntity> getCity(Int)
+ Flow<List<CityEntity>> getListOFCities()
}

interface com.example.parasol.network.NominatimSearchApiService {
+ List<City> searchCities(String,String)
}

interface com.example.parasol.data.AppContainer {
+ CitiesRepository citiesRepository
}

class com.example.parasol.ui.home.ForecastGroup {
+ <<Create>> ForecastGroup(UvRiskLevel,MutableList<Forecast>)
}

enum com.example.parasol.utils.UvRiskLevel {
+  LOW
+  MODERATE
+  HIGH
+  VERY_HIGH
+  EXTREMELY_HIGH
}

class com.example.parasol.hilt.NetworkModule {
-  GEOCODING_BASE_URL
-  UV_INDEX_BASE_URL
+ OkHttpClient provideOkHttpClient()
+ Gson provideGson()
+ NominatimSearchApiService provideGeocodingSearchApiService(OkHttpClient,Gson)
+ NominatimReverseApiService provideGeocodingReverseApiService(OkHttpClient,Gson)
+ CurrentUvApiService provideStopLightApiService(OkHttpClient,Gson)
}


class com.example.parasol.hilt.DatabaseModule {
+ CityDao provideCityDao(CitiesDatabase)
+ CitiesDatabase provideCitiesDatabase(Context)
}

class com.example.parasol.ui.Screen$Home {
}
class com.example.parasol.ui.Screen$CitySearch {
}
class com.example.parasol.ui.Screen {
+ <<Create>> Screen(String)
}

class com.example.parasol.ui.home.IndexUiState$Loading {
}
class com.example.parasol.ui.home.IndexUiState$Success {
+ <<Create>> Success(UvResponse)
}

class com.example.parasol.ui.home.IndexUiState$Error {
+ <<Create>> Error(String)
}

class com.example.parasol.ui.home.IndexUiState {
}
note top of com.example.parasol.ui.home.IndexUiState
/**
 * Represents the UI state for the UV index.
 */
end note

class com.example.parasol.ui.home.HomeViewModel$Companion {
-  TIMEOUT_MILLIS
-  NO_CITIES_AVAILABLE
-  CITY_NOT_SELECTED
-  CITY_NOT_FOUND
-  CITY_ID_NOT_FOUND
}

class com.example.parasol.ui.home.HomeViewModel {
-  _indexUiState
+ StateFlow<IndexUiState> indexUiState
-  _selectedCityId
+ StateFlow<Int?> selectedCityId
+ StateFlow<HomeUiState> homeUiState
+ <<Create>> HomeViewModel(FetchUVDataUseCase,CitiesRepository,UserPreferencesRepository)
+ void retryAction()
- void loadCities()
- void observeSelectedCity()
- void loadCityCoordinatesAndGetUV()
+ void setSelectedCity(CityEntity?)
- void getUVIs(Double,Double)
}
note top of com.example.parasol.ui.home.HomeViewModel
/**
 * ViewModel for managing home-related data and UI state.
 *
 * @property citiesRepository Repository for city data.
 * @property userPreferencesRepository Repository for user preferences.
 */
end note

note left of com.example.parasol.ui.home.HomeViewModel::homeUiState
/**
     * The current state of the home UI, which includes a list of cities.
     */
end note

note left of com.example.parasol.ui.home.HomeViewModel::loadCities()
/**
     * Loads cities from the repository and updates the selected city ID if necessary.
     */
end note
note right of com.example.parasol.ui.home.HomeViewModel::observeSelectedCity()
/**
     * Observes changes to the selected city from user preferences.
     */
end note
note left of com.example.parasol.ui.home.HomeViewModel::loadCityCoordinatesAndGetUV()
/**
     * Loads coordinates for the selected city and fetches the UV index.
     */
end note
note right of com.example.parasol.ui.home.HomeViewModel::setSelectedCity(CityEntity?)
/**
     * Sets the currently selected city and saves it to user preferences.
     *
     * @param city The selected CityEntity.
     */
end note
note left of com.example.parasol.ui.home.HomeViewModel::getUVIs(Double,Double)
/**
     * Fetches UV index values based on latitude and longitude.
     *
     * @param latitude The latitude of the location.
     * @param longitude The longitude of the location.
     */
end note

class com.example.parasol.ui.home.HomeUiState {
+ <<Create>> HomeUiState(List<CityEntity>)
}
note top of com.example.parasol.ui.home.HomeUiState
/**
 * Represents the UI state for home, including a list of cities.
 *
 * @property citiesList A list of available CityEntity objects.
 */
end note


interface com.example.parasol.data.CitiesRepository {
+ StateFlow<Int?> selectedCityId
+ Flow<List<CityEntity>> getFullListOfCities()
+ Flow<CityEntity?> getOneCity(Int)
+ void insertCity(CityEntity)
+ void deleteCity(CityEntity)
+ void updateCity(CityEntity)
}

note left of com.example.parasol.data.CitiesRepository::getFullListOfCities()
/**
     * Retrieve all the items from the the given data source.
     */
end note
note right of com.example.parasol.data.CitiesRepository::getOneCity(Int)
/**
     * Retrieve an item from the given data source that matches with the [id].
     */
end note
note left of com.example.parasol.data.CitiesRepository::insertCity(CityEntity)
/**
     * Insert item in the data source
     */
end note
note right of com.example.parasol.data.CitiesRepository::deleteCity(CityEntity)
/**
     * Delete item from the data source
     */
end note
note left of com.example.parasol.data.CitiesRepository::updateCity(CityEntity)
/**
     * Update item in the data source
     */
end note

class com.example.parasol.utils.ErrorHandler {
+ String handleError(Exception)
}

class com.example.parasol.network.model.City {
+ <<Create>> City(AddressData,String,Double,Double,String)
}

class com.example.parasol.network.model.AddressData {
+ <<Create>> AddressData(String,String)
}

class com.example.parasol.ParasolApplication {
- AppContainer container
+ void onCreate()
}


class com.example.parasol.hilt.RepositoryModule {
+ CitiesRepository provideCitiesRepository(CityDao)
}

class com.example.parasol.hilt.AppModule {
+ Context provideApplicationContext(Application)
}

class com.example.parasol.MainActivity {
+ void onCreate(Bundle?)
}

class com.example.parasol.network.model.UvResponse {
+ <<Create>> UvResponse(Double,Double,CurrentUv,List<Forecast>)
}

class com.example.parasol.network.model.CurrentUv {
+ <<Create>> CurrentUv(String,Double)
}

class com.example.parasol.network.model.Forecast {
+ <<Create>> Forecast(String,Double)
}

class com.example.parasol.data.CitiesDatabase$Companion {
- CitiesDatabase? Instance
+ CitiesDatabase getDatabase(Context)
}


abstract class com.example.parasol.data.CitiesDatabase {
+ CityDao cityDao()
}

class com.example.parasol.ui.theme.ExtendedColorScheme {
+ <<Create>> ExtendedColorScheme(ColorFamily,ColorFamily,ColorFamily,ColorFamily,ColorFamily)
}

class com.example.parasol.ui.theme.ColorFamily {
+ <<Create>> ColorFamily(Color,Color,Color,Color)
}

class com.example.parasol.ui.citySelection.CitySelectionViewModel {
-  _citiesList
+ StateFlow<List<CityEntity>> citiesList
-  _selectedCityId
+ StateFlow<Int?> selectedCityId
+ <<Create>> CitySelectionViewModel(CitiesRepository,UserPreferencesRepository)
- void loadCities()
- void observeSelectedCity()
+ void setSelectedCity(CityEntity?)
}


class com.example.parasol.data.CityEntity {
+ <<Create>> CityEntity(Int,String,Double,Double)
}

class com.example.parasol.ui.UVIndexViewModel {
-  _indexUiState
+ StateFlow<IndexUiState> indexUiState
+ <<Create>> UVIndexViewModel(FetchUVDataUseCase,CitiesRepository)
- void observeCitySelection()
- void loadCityCoordinatesAndGetUV(Int)
- void getUVIs(Double,Double)
}


class com.example.parasol.utils.useCases.GetCitiesUseCase {
+ <<Create>> GetCitiesUseCase(CitiesRepository)
+ List<CityEntity> invoke()
}

class com.example.parasol.data.OfflineCitiesRepository {
-  _selectedCityId
+ StateFlow<Int?> selectedCityId
+ <<Create>> OfflineCitiesRepository(CityDao)
+ Flow<List<CityEntity>> getFullListOfCities()
+ Flow<CityEntity?> getOneCity(Int)
+ void insertCity(CityEntity)
+ void deleteCity(CityEntity)
+ void updateCity(CityEntity)
+ void setSelectedCityId(Int?)
}


interface com.example.parasol.network.NominatimReverseApiService {
+ City searchCities(Double,Double,String)
}

class com.example.parasol.ui.home.HomeFragment {
- CitySelectionViewModel citySelectionViewModel
- UVIndexViewModel uvIndexViewModel
+ void onViewCreated(View,Bundle?)
}


class com.example.parasol.ui.citySearch.SearchUiState$Loading {
}
class com.example.parasol.ui.citySearch.SearchUiState$Success {
+ <<Create>> Success(List<City>)
}

class com.example.parasol.ui.citySearch.SearchUiState$Error {
}
class com.example.parasol.ui.citySearch.SearchUiState {
}
class com.example.parasol.ui.citySearch.ReverseSearchUiState$Loading {
}
class com.example.parasol.ui.citySearch.ReverseSearchUiState$Success {
+ <<Create>> Success(City)
}

class com.example.parasol.ui.citySearch.ReverseSearchUiState$Error {
}
class com.example.parasol.ui.citySearch.ReverseSearchUiState {
}
class com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$PermissionDenied {
}
class com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$LocationUnavailable {
}
class com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$GenericError {
+ <<Create>> GenericError(String)
}

class com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType {
}
class com.example.parasol.ui.citySearch.CitySearchViewModel {
-  _citySearchUiState
+ StateFlow<SearchUiState> citySearchUiState
-  _cityReverseUiState
+ StateFlow<ReverseSearchUiState> cityReverseUiState
- Job? searchJob
-  minQueryLength
-  debounceDelay
+ StateFlow<HomeUiState> homeUiState
+  location
-  errorMessage
+ <<Create>> CitySearchViewModel(CitiesRepository,NominatimSearchApiService,NominatimReverseApiService)
+ void searchCityByName(String)
+ void searchCityByCurrentLocation()
- void searchCityByCoordinates(Double,Double)
+ void addCityToRepository(City)
+ void deleteCity(CityEntity)
- void updateLocation(Location)
+ void setError(ErrorType)
+ void getCurrentLocation(Context)
}


class com.example.parasol.data.AppDataContainer {
+ CitiesRepository citiesRepository
+ <<Create>> AppDataContainer(Context)
}




com.example.parasol.data.UserPreferencesRepository +.. com.example.parasol.data.UserPreferencesRepository$PreferencesKeys
com.example.parasol.ui.Screen +.. com.example.parasol.ui.Screen$Home
com.example.parasol.ui.Screen <|-- com.example.parasol.ui.Screen$Home
com.example.parasol.ui.Screen +.. com.example.parasol.ui.Screen$CitySearch
com.example.parasol.ui.Screen <|-- com.example.parasol.ui.Screen$CitySearch
com.example.parasol.ui.home.IndexUiState +.. com.example.parasol.ui.home.IndexUiState$Loading
com.example.parasol.ui.home.IndexUiState <|-- com.example.parasol.ui.home.IndexUiState$Loading
com.example.parasol.ui.home.IndexUiState +.. com.example.parasol.ui.home.IndexUiState$Success
com.example.parasol.ui.home.IndexUiState <|-- com.example.parasol.ui.home.IndexUiState$Success
com.example.parasol.ui.home.IndexUiState +.. com.example.parasol.ui.home.IndexUiState$Error
com.example.parasol.ui.home.IndexUiState <|-- com.example.parasol.ui.home.IndexUiState$Error
com.example.parasol.ui.home.HomeViewModel +.. com.example.parasol.ui.home.HomeViewModel$Companion
androidx.lifecycle.ViewModel <|-- com.example.parasol.ui.home.HomeViewModel
android.app.Application <|-- com.example.parasol.ParasolApplication
androidx.activity.ComponentActivity <|-- com.example.parasol.MainActivity
com.example.parasol.data.CitiesDatabase +.. com.example.parasol.data.CitiesDatabase$Companion
androidx.room.RoomDatabase <|-- com.example.parasol.data.CitiesDatabase
androidx.lifecycle.ViewModel <|-- com.example.parasol.ui.citySelection.CitySelectionViewModel
androidx.lifecycle.ViewModel <|-- com.example.parasol.ui.UVIndexViewModel
com.example.parasol.data.CitiesRepository <|.. com.example.parasol.data.OfflineCitiesRepository
androidx.fragment.app.Fragment <|-- com.example.parasol.ui.home.HomeFragment
com.example.parasol.ui.citySearch.SearchUiState +.. com.example.parasol.ui.citySearch.SearchUiState$Loading
com.example.parasol.ui.citySearch.SearchUiState <|-- com.example.parasol.ui.citySearch.SearchUiState$Loading
com.example.parasol.ui.citySearch.SearchUiState +.. com.example.parasol.ui.citySearch.SearchUiState$Success
com.example.parasol.ui.citySearch.SearchUiState <|-- com.example.parasol.ui.citySearch.SearchUiState$Success
com.example.parasol.ui.citySearch.SearchUiState +.. com.example.parasol.ui.citySearch.SearchUiState$Error
com.example.parasol.ui.citySearch.SearchUiState <|-- com.example.parasol.ui.citySearch.SearchUiState$Error
com.example.parasol.ui.citySearch.ReverseSearchUiState +.. com.example.parasol.ui.citySearch.ReverseSearchUiState$Loading
com.example.parasol.ui.citySearch.ReverseSearchUiState <|-- com.example.parasol.ui.citySearch.ReverseSearchUiState$Loading
com.example.parasol.ui.citySearch.ReverseSearchUiState +.. com.example.parasol.ui.citySearch.ReverseSearchUiState$Success
com.example.parasol.ui.citySearch.ReverseSearchUiState <|-- com.example.parasol.ui.citySearch.ReverseSearchUiState$Success
com.example.parasol.ui.citySearch.ReverseSearchUiState +.. com.example.parasol.ui.citySearch.ReverseSearchUiState$Error
com.example.parasol.ui.citySearch.ReverseSearchUiState <|-- com.example.parasol.ui.citySearch.ReverseSearchUiState$Error
com.example.parasol.ui.citySearch.ErrorType +.. com.example.parasol.ui.citySearch.ErrorType$PermissionDenied
com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType +.. com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$PermissionDenied
com.example.parasol.ui.citySearch.ErrorType <|-- com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$PermissionDenied
com.example.parasol.ui.citySearch.ErrorType +.. com.example.parasol.ui.citySearch.ErrorType$LocationUnavailable
com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType +.. com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$LocationUnavailable
com.example.parasol.ui.citySearch.ErrorType <|-- com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$LocationUnavailable
com.example.parasol.ui.citySearch.ErrorType +.. com.example.parasol.ui.citySearch.ErrorType$GenericError
com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType +.. com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$GenericError
com.example.parasol.ui.citySearch.ErrorType <|-- com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType$GenericError
com.example.parasol.ui.citySearch.CitySearchViewModel +.. com.example.parasol.ui.citySearch.CitySearchViewModel$ErrorType
androidx.lifecycle.ViewModel <|-- com.example.parasol.ui.citySearch.CitySearchViewModel
com.example.parasol.data.AppContainer <|.. com.example.parasol.data.AppDataContainer
@enduml